const execute = async (country) =>  {
    const timeZones = {
        'Afghanistan': ['Asia/Kabul'],
        'Albania': ['Europe/Tirane'],
        'Algeria': ['Africa/Algiers'],
        'Andorra': ['Europe/Andorra'],
        'Angola': ['Africa/Luanda'],
        'Antigua and Barbuda': ['America/Antigua'],
        'Argentina': ['America/Argentina/Buenos_Aires', 'America/Argentina/Cordoba'],
        'Armenia': ['Asia/Yerevan'],
        'Australia': ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane', 'Australia/Perth'],
        'Austria': ['Europe/Vienna'],
        'Azerbaijan': ['Asia/Baku'],
        'Bahamas': ['America/Nassau'],
        'Bahrain': ['Asia/Bahrain'],
        'Bangladesh': ['Asia/Dhaka'],
        'Barbados': ['America/Barbados'],
        'Belarus': ['Europe/Minsk'],
        'Belgium': ['Europe/Brussels'],
        'Belize': ['America/Belize'],
        'Benin': ['Africa/Porto-Novo'],
        'Bhutan': ['Asia/Thimphu'],
        'Bolivia': ['America/La_Paz'],
        'Bosnia and Herzegovina': ['Europe/Sarajevo'],
        'Botswana': ['Africa/Gaborone'],
        'Brazil': ['America/Sao_Paulo', 'America/Manaus', 'America/Rio_Branco'],
        'Brunei': ['Asia/Brunei'],
        'Bulgaria': ['Europe/Sofia'],
        'Burkina Faso': ['Africa/Ouagadougou'],
        'Burundi': ['Africa/Bujumbura'],
        'Cabo Verde': ['Atlantic/Cape_Verde'],
        'Cambodia': ['Asia/Phnom_Penh'],
        'Cameroon': ['Africa/Douala'],
        'Canada': ['America/Toronto', 'America/Vancouver', 'America/Edmonton', 'America/Winnipeg', 'America/Halifax'],
        'Central African Republic': ['Africa/Bangui'],
        'Chad': ['Africa/Ndjamena'],
        'Chile': ['America/Santiago'],
        'China': ['Asia/Shanghai', 'Asia/Urumqi'],
        'Colombia': ['America/Bogota'],
        'Comoros': ['Indian/Comoro'],
        'Congo, Democratic Republic of the': ['Africa/Kinshasa', 'Africa/Lubumbashi'],
        'Congo, Republic of the': ['Africa/Brazzaville'],
        'Costa Rica': ['America/Costa_Rica'],
        'Croatia': ['Europe/Zagreb'],
        'Cuba': ['America/Havana'],
        'Cyprus': ['Asia/Nicosia'],
        'Czech Republic': ['Europe/Prague'],
        'Denmark': ['Europe/Copenhagen'],
        'Djibouti': ['Africa/Djibouti'],
        'Dominica': ['America/Dominica'],
        'Dominican Republic': ['America/Santo_Domingo'],
        'Ecuador': ['America/Guayaquil'],
        'Egypt': ['Africa/Cairo'],
        'El Salvador': ['America/El_Salvador'],
        'Equatorial Guinea': ['Africa/Malabo'],
        'Eritrea': ['Africa/Asmara'],
        'Estonia': ['Europe/Tallinn'],
        'Eswatini': ['Africa/Mbabane'],
        'Ethiopia': ['Africa/Addis_Ababa'],
        'Fiji': ['Pacific/Fiji'],
        'Finland': ['Europe/Helsinki'],
        'France': ['Europe/Paris'],
        'Gabon': ['Africa/Libreville'],
        'Gambia': ['Africa/Banjul'],
        'Georgia': ['Asia/Tbilisi'],
        'Germany': ['Europe/Berlin'],
        'Ghana': ['Africa/Accra'],
        'Greece': ['Europe/Athens'],
        'Grenada': ['America/Grenada'],
        'Guatemala': ['America/Guatemala'],
        'Guinea': ['Africa/Conakry'],
        'Guinea-Bissau': ['Africa/Bissau'],
        'Guyana': ['America/Guyana'],
        'Haiti': ['America/Port-au-Prince'],
        'Honduras': ['America/Tegucigalpa'],
        'Hungary': ['Europe/Budapest'],
        'Iceland': ['Atlantic/Reykjavik'],
        'India': ['Asia/Kolkata'],
        'Indonesia': ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura'],
        'Iran': ['Asia/Tehran'],
        'Iraq': ['Asia/Baghdad'],
        'Ireland': ['Europe/Dublin'],
        'Israel': ['Asia/Jerusalem'],
        'Italy': ['Europe/Rome'],
        'Jamaica': ['America/Jamaica'],
        'Japan': ['Asia/Tokyo'],
        'Jordan': ['Asia/Amman'],
        'Kazakhstan': ['Asia/Almaty', 'Asia/Qyzylorda', 'Asia/Aqtobe', 'Asia/Atyrau', 'Asia/Oral'],
        'Kenya': ['Africa/Nairobi'],
        'Kiribati': ['Pacific/Tarawa', 'Pacific/Enderbury', 'Pacific/Kiritimati'],
        'Korea, North': ['Asia/Pyongyang'],
        'Korea, South': ['Asia/Seoul'],
        'Kuwait': ['Asia/Kuwait'],
        'Kyrgyzstan': ['Asia/Bishkek'],
        'Laos': ['Asia/Vientiane'],
        'Latvia': ['Europe/Riga'],
        'Lebanon': ['Asia/Beirut'],
        'Lesotho': ['Africa/Maseru'],
        'Liberia': ['Africa/Monrovia'],
        'Libya': ['Africa/Tripoli'],
        'Liechtenstein': ['Europe/Vaduz'],
        'Lithuania': ['Europe/Vilnius'],
        'Luxembourg': ['Europe/Luxembourg'],
        'Madagascar': ['Indian/Antananarivo'],
        'Malawi': ['Africa/Blantyre'],
        'Malaysia': ['Asia/Kuala_Lumpur'],
        'Maldives': ['Asia/Male'],
        'Mali': ['Africa/Bamako'],
        'Malta': ['Europe/Valletta'],
        'Marshall Islands': ['Pacific/Majuro'],
        'Mauritania': ['Africa/Nouakchott'],
        'Mauritius': ['Indian/Mauritius'],
        'Mexico': ['America/Mexico_City', 'America/Tijuana', 'America/Monterrey'],
        'Micronesia': ['Pacific/Chuuk', 'Pacific/Pohnpei', 'Pacific/Kosrae'],
        'Moldova': ['Europe/Chisinau'],
        'Monaco': ['Europe/Monaco'],
        'Mongolia': ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
        'Montenegro': ['Europe/Podgorica'],
        'Morocco': ['Africa/Casablanca'],
        'Mozambique': ['Africa/Maputo'],
        'Myanmar': ['Asia/Yangon'],
        'Namibia': ['Africa/Windhoek'],
        'Nauru': ['Pacific/Nauru'],
        'Nepal': ['Asia/Kathmandu'],
        'Netherlands': ['Europe/Amsterdam'],
        'New Zealand': ['Pacific/Auckland', 'Pacific/Chatham'],
        'Nicaragua': ['America/Managua'],
        'Niger': ['Africa/Niamey'],
        'Nigeria': ['Africa/Lagos'],
        'North Macedonia': ['Europe/Skopje'],
        'Norway': ['Europe/Oslo'],
        'Oman': ['Asia/Muscat'],
        'Pakistan': ['Asia/Karachi'],
        'Palau': ['Pacific/Palau'],
        'Palestine': ['Asia/Gaza', 'Asia/Hebron'],
        'Panama': ['America/Panama'],
        'Papua New Guinea': ['Pacific/Port_Moresby'],
        'Paraguay': ['America/Asuncion'],
        'Peru': ['America/Lima'],
        'Philippines': ['Asia/Manila'],
        'Poland': ['Europe/Warsaw'],
        'Portugal': ['Europe/Lisbon', 'Atlantic/Azores'],
        'Qatar': ['Asia/Qatar'],
        'Romania': ['Europe/Bucharest'],
        'Russia': [
            'Europe/Moscow', 'Europe/Samara', 'Asia/Yekaterinburg',
            'Asia/Omsk', 'Asia/Krasnoyarsk', 'Asia/Irkutsk',
            'Asia/Vladivostok', 'Asia/Magadan', 'Asia/Kamchatka'
        ],
        'Rwanda': ['Africa/Kigali'],
        'Saint Kitts and Nevis': ['America/St_Kitts'],
        'Saint Lucia': ['America/St_Lucia'],
        'Saint Vincent and the Grenadines': ['America/St_Vincent'],
        'Samoa': ['Pacific/Apia'],
        'San Marino': ['Europe/San_Marino'],
        'Sao Tome and Principe': ['Africa/Sao_Tome'],
        'Saudi Arabia': ['Asia/Riyadh'],
        'Senegal': ['Africa/Dakar'],
        'Serbia': ['Europe/Belgrade'],
        'Seychelles': ['Indian/Mahe'],
        'Sierra Leone': ['Africa/Freetown'],
        'Singapore': ['Asia/Singapore'],
        'Slovakia': ['Europe/Bratislava'],
        'Slovenia': ['Europe/Ljubljana'],
        'Solomon Islands': ['Pacific/Guadalcanal'],
        'Somalia': ['Africa/Mogadishu'],
        'South Africa': ['Africa/Johannesburg'],
        'South Sudan': ['Africa/Juba'],
        'Spain': ['Europe/Madrid', 'Atlantic/Canary'],
        'Sri Lanka': ['Asia/Colombo'],
        'Sudan': ['Africa/Khartoum'],
        'Suriname': ['America/Paramaribo'],
        'Sweden': ['Europe/Stockholm'],
        'Switzerland': ['Europe/Zurich'],
        'Syria': ['Asia/Damascus'],
        'Taiwan': ['Asia/Taipei'],
        'Tajikistan': ['Asia/Dushanbe'],
        'Tanzania': ['Africa/Dar_es_Salaam'],
        'Thailand': ['Asia/Bangkok'],
        'Timor-Leste': ['Asia/Dili'],
        'Togo': ['Africa/Lome'],
        'Tonga': ['Pacific/Tongatapu'],
        'Trinidad and Tobago': ['America/Port_of_Spain'],
        'Tunisia': ['Africa/Tunis'],
        'Turkey': ['Europe/Istanbul'],
        'Turkmenistan': ['Asia/Ashgabat'],
        'Tuvalu': ['Pacific/Funafuti'],
        'Uganda': ['Africa/Kampala'],
        'Ukraine': ['Europe/Kiev'],
        'United Arab Emirates': ['Asia/Dubai'],
        'United Kingdom': ['Europe/London'],
        'United States': [
            'America/New_York', 'America/Los_Angeles', 'America/Chicago',
            'America/Denver', 'America/Phoenix', 'America/Indianapolis'
        ],
        'Uruguay': ['America/Montevideo'],
        'Uzbekistan': ['Asia/Tashkent'],
        'Vanuatu': ['Pacific/Efate'],
        'Vatican City': ['Europe/Vatican'],
        'Venezuela': ['America/Caracas'],
        'Vietnam': ['Asia/Ho_Chi_Minh'],
        'Yemen': ['Asia/Aden'],
        'Zambia': ['Africa/Lusaka'],
        'Zimbabwe': ['Africa/Harare']
    };

    const timeZoneList = timeZones[country];
    if (!timeZoneList) {
        return `Time zone not found for ${country}.`;
    }

    // Use the first time zone from the list
    const firstTimeZone = timeZoneList[0];
    const currentTime = new Date().toLocaleString('en-US', { timeZone: firstTimeZone });

    return `The current time in ${country} (${firstTimeZone}) is: ${currentTime}.`;
}

// Function details for the time retrieval
const details = {
    type: "function",
    function: {
        name: 'world_clock',
        parameters: {
            type: 'object',
            properties: {
                country: {
                    type: 'string',
                    description: 'The name of the country to get the current local time for.'
                }
            },
            required: ['country']
        },
    },
    description: 'This function retrieves the current local time for a specified country. If the country has multiple time zones, it returns the time for the first time zone in the list. If the country is not found, an appropriate message is returned.'
};

// Example usage of the function
console.log(execute('Guinea-Bissau')); // Retrieves the current time in Guinea-Bissau
console.log(execute('United States')); // Retrieves the current time in the first time zone for the USA
console.log(execute('InvalidCountry')); // Returns a message indicating the country was not found
export { execute, details };
