[{
    "Afghanistan": "GMT+4:30",
    "Albania": "GMT+1",
    "Algeria": "GMT+1",
    "Andorra": "GMT+1",
    "Angola": "GMT+1",
    "Antigua and Barbuda": "GMT-4",
    "Argentina": "GMT-3",
    "Armenia": "GMT+4",
    "Australia": "GMT+10",
    "Austria": "GMT+1",
    "Azerbaijan": "GMT+4",
    "Bahamas": "GMT-5",
    "Bahrain": "GMT+3",
    "Bangladesh": "GMT+6",
    "Barbados": "GMT-4",
    "Belarus": "GMT+3",
    "Belgium": "GMT+1",
    "Belize": "GMT-6",
    "Benin": "GMT+1",
    "Bhutan": "GMT+6",
    "Bolivia": "GMT-4",
    "Bosnia and Herzegovina": "GMT+1",
    "Botswana": "GMT+2",
    "Brazil": "GMT-3",
    "Brunei": "GMT+8",
    "Bulgaria": "GMT+2",
    "Burkina Faso": "GMT",
    "Burundi": "GMT+2",
    "Cabo Verde": "GMT-1",
    "Cambodia": "GMT+7",
    "Cameroon": "GMT+1",
    "Canada": "GMT-5",
    "Central African Republic": "GMT+1",
    "Chad": "GMT+1",
    "Chile": "GMT-3",
}   ]
